# Generated by Django 4.1.3 on 2022-11-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atom', '0002_rename_person_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telugu', models.PositiveIntegerField(blank=True, null=True)),
                ('English', models.PositiveIntegerField(blank=True, null=True)),
                ('Mathematics', models.PositiveIntegerField(blank=True, null=True)),
                ('Biology', models.PositiveIntegerField(blank=True, null=True)),
                ('Physics', models.PositiveIntegerField(blank=True, null=True)),
                ('Chemistry', models.PositiveIntegerField(blank=True, null=True)),
                ('Social', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atom.people')),
            ],
        ),
    ]
