# Generated by Django 4.1.3 on 2022-11-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atom', '0008_author_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.SlugField(),
        ),
    ]
