# Generated by Django 4.1.3 on 2022-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atom', '0009_alter_entry_body_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
